try{
    data="Hello World";
    //console.log(z)
    throw "Manual error!"
}
catch(err){
    console.log("Error occurred: "+err)
}